import {Rubik} from "next/font/google";
import "./globals.css";

import {UserProvider} from '@auth0/nextjs-auth0/client'
import Nav from "@/components/shared/Nav";

const rubikRegular = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
  weight: ['400'],
})

export const metadata = {
  title: "E Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Bymphony</title>
      </head>

      <body
          className={`${rubikRegular.variable} flex flex-col bg-page font-rubik`}>
      <Nav />
      {children}
      </body>
    </html>
  );
}
